server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mahasiswa
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
